name: PR

on:
  # Trigger the workflow on push or pull request for master, dev and preprod
  push:
    branches:
      - master
      - dev
      - preprod
  pull_request:
    branches:
      - dev
      - preprod
jobs:
  send-team-notification:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.WEBHOOK_URI }}
          title: ''
          # Message summary
          summary: 'GitHub Actions Message'
          # Message text
          text: ''
          # Message theme color
          theme_color: ''
          # JSON array for message sections
          sections: '[{ "activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png", "activityTitle": "GitHub Action invoked",  "activitySubtitle": "Event triggered by ${{ github.event.head_commit.author.name }}", "activityText": "Commit message: [${{ github.event.head_commit.message}}](${{ github.event.head_commit.url }})" }]'
          # JSON array for message actions
          actions: '[{ "@type": "OpenUri", "name": "View Commit", "targets": [{ "os": "default", "uri": "${{ github.event.head_commit.url }}" }] }]'
