name: PR

on:
  # Trigger the workflow on push or pull request,
  # but only for the dev branch
  pull_request:
    branches:
      - dev
jobs:
  send-team-notification:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: https://adaptivestackinc.webhook.office.com/webhookb2/f005c5f4-a27b-4892-9004-c2f0cf73245b@74d4c0f8-eff1-47bd-85d7-cadf3cf8718e/IncomingWebhook/5e47e85b8a34485983810b79f29756e2/d11786a1-618e-4ee6-b1d8-9e42bcb26ae1
          title: 'New Pull Request Has Been Created'
          # Message summary
          summary: 'Please Review Pull Request on Github'
          # Message text
          text: 'Please Review Pull Request on Github'
          # Message theme color
          theme_color: ''
          # JSON array for message sections
          sections: ''
          # JSON array for message actions
          actions: ''